import type { Scheme } from "../types/scheme";
import type { CitizenProfile } from "../types/citizen";
import type { CitizenDocument } from "../types/document";
import type { Application } from "../types/application";
import type { Notification } from "../types/notification";

export const mockProfile: CitizenProfile = {
  id: "citizen-001",
  name: "Priya Sharma",
  email: "priya.sharma@email.com",
  mobile: "+91 98765 43210",
  age: 27,
  gender: "Female",
  state: "Maharashtra",
  district: "Pune",
  pincode: "411001",
  educationLevel: "Graduate",
  isStudent: false,
  employmentStatus: "Self-Employed",
  occupation: "Artisan / Craftsperson",
  incomeRange: "1–2.5 LPA",
  familySize: 4,
  hasDisability: false,
  category: "OBC",
  completionPercentage: 74,
};

export const mockSchemes: Scheme[] = [
  {
    id: "pm-vishwakarma",
    name: "PM Vishwakarma Yojana",
    department: "Ministry of Micro, Small & Medium Enterprises",
    ministry: "MSME",
    category: "Employment",
    description:
      "Supports traditional artisans and craftspeople with skill training, toolkits, credit support, and market linkage to help them grow their craft-based businesses.",
    benefits: [
      "Up to ₹3 lakh collateral-free credit at 5% interest",
      "₹500/day stipend during skill training",
      "Free toolkit worth ₹15,000",
      "PM Vishwakarma certificate and ID card",
      "Digital transaction incentive",
    ],
    eligibilityCriteria: [
      { label: "Age", value: "18 years or above", met: true },
      { label: "Occupation", value: "Traditional artisan or craftsperson", met: true },
      { label: "Category", value: "Open to all categories", met: true },
      { label: "Family member restriction", value: "One per family", met: true, needsVerification: false },
    ],
    requiredDocuments: ["Aadhaar Card", "Mobile linked with Aadhaar", "Bank account details", "Ration Card / Family ID"],
    applicationProcess: [
      "Register at CSC (Common Service Centre) or PM Vishwakarma portal",
      "Verify Aadhaar biometrically at CSC",
      "Gram Panchayat / ULB verification",
      "Complete basic and advanced skill training",
      "Apply for credit support through empanelled bank",
    ],
    importantInfo: "This scheme is implemented through Common Service Centres. Visit your nearest CSC to begin the process.",
    matchPercentage: 94,
    state: "All India",
    isCentral: true,
    tags: ["artisan", "skill", "credit", "msme"],
  },
  {
    id: "pm-awas-yojana-urban",
    name: "PM Awas Yojana – Urban",
    department: "Ministry of Housing and Urban Affairs",
    ministry: "MoHUA",
    category: "Housing",
    description:
      "Provides housing assistance to economically weaker sections and low-income groups in urban areas through credit-linked subsidy and direct benefit transfer.",
    benefits: [
      "Interest subsidy up to 6.5% on home loans",
      "Central assistance of ₹1.5 lakh for house construction",
      "Technology Innovation Grant for affordable housing",
    ],
    eligibilityCriteria: [
      { label: "Income (EWS)", value: "Up to ₹3 lakh annual income", met: true },
      { label: "Income (LIG)", value: "₹3–6 lakh annual income" },
      { label: "No pucca house", value: "Beneficiary family should not own a pucca house", met: true },
      { label: "First-time home buyer", value: "Applicable for CLSS component", needsVerification: true },
    ],
    requiredDocuments: [
      "Aadhaar Card",
      "Income Certificate",
      "Property documents / site allotment letter",
      "Bank account details",
    ],
    applicationProcess: [
      "Apply online at pmaymis.gov.in or through ULB",
      "Upload required documents",
      "Aadhaar verification",
      "Field verification by ULB officer",
      "Approval and fund disbursement",
    ],
    importantInfo:
      "For CLSS component, apply through an empanelled Primary Lending Institution (bank/HFC). Final eligibility is determined by the relevant authority.",
    matchPercentage: 81,
    state: "All India",
    isCentral: true,
    tags: ["housing", "home loan", "urban", "subsidy"],
  },
  {
    id: "beti-bachao",
    name: "Beti Bachao Beti Padhao",
    department: "Ministry of Women and Child Development",
    ministry: "WCD",
    category: "Women & Child",
    description:
      "A multi-sectoral programme to address the declining child sex ratio and promote welfare and education of the girl child across India.",
    benefits: [
      "Conditional cash transfers for girl child education",
      "Sukanya Samriddhi Yojana integration",
      "Awareness and training programmes",
      "Scholarship support for higher education",
    ],
    eligibilityCriteria: [
      { label: "Gender", value: "Girl child", met: true },
      { label: "Age", value: "Birth to 10 years for Sukanya component", met: false },
      { label: "Residency", value: "Indian resident", met: true },
    ],
    requiredDocuments: ["Birth Certificate", "Aadhaar of parent/guardian", "Bank account in child's name"],
    applicationProcess: [
      "Visit nearest post office or bank for Sukanya Samriddhi Account",
      "Fill application form with required documents",
      "Deposit minimum ₹250 to open account",
      "Account matures when girl turns 21",
    ],
    importantInfo: "Scheme components vary by state. Check your state government portal for state-specific benefits.",
    matchPercentage: 67,
    state: "All India",
    isCentral: true,
    tags: ["girl child", "education", "savings", "women"],
  },
  {
    id: "pmkvy",
    name: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)",
    department: "Ministry of Skill Development and Entrepreneurship",
    ministry: "MSDE",
    category: "Employment",
    description:
      "India's flagship skill certification scheme enabling youth to take up industry-relevant skill training and gain recognized certifications to improve employability.",
    benefits: [
      "Free skill training by NSDC-empanelled partners",
      "Monetary reward on certification",
      "Recognition of Prior Learning (RPL) for existing skills",
      "Placement support",
    ],
    eligibilityCriteria: [
      { label: "Age", value: "15–45 years", met: true },
      { label: "Education", value: "No minimum qualification for most courses", met: true },
      { label: "Nationality", value: "Indian citizen", met: true },
    ],
    requiredDocuments: ["Aadhaar Card", "Bank account details", "Age proof"],
    applicationProcess: [
      "Register on skillindiadigital.gov.in",
      "Select course and nearest training centre",
      "Attend training (typically 150–300 hours)",
      "Appear for assessment",
      "Receive certification from NSDC/sector skill council",
    ],
    importantInfo: "Training is available in 300+ job roles across 30+ sectors. Courses can be online or in-person.",
    matchPercentage: 88,
    state: "All India",
    isCentral: true,
    tags: ["skill", "training", "employment", "youth", "certification"],
  },
  {
    id: "ayushman-bharat",
    name: "Ayushman Bharat PM-JAY",
    department: "Ministry of Health and Family Welfare",
    ministry: "MoHFW",
    category: "Health",
    description:
      "Provides health cover of ₹5 lakh per family per year for secondary and tertiary hospitalisation to economically vulnerable families across India.",
    benefits: [
      "₹5 lakh annual health coverage per family",
      "Cashless treatment at empanelled hospitals",
      "Covers pre-existing conditions",
      "No cap on family size or age",
      "Over 1,900 medical procedures covered",
    ],
    eligibilityCriteria: [
      { label: "Income", value: "Based on SECC 2011 database / deprivation criteria", needsVerification: true },
      { label: "Family composition", value: "Any family size", met: true },
      { label: "State scheme integration", value: "Some states have expanded coverage", met: true },
    ],
    requiredDocuments: ["Aadhaar / any government ID", "Ration card (for SECC verification)"],
    applicationProcess: [
      "Check eligibility at pmjay.gov.in or call 14555",
      "Visit nearest Common Service Centre or Ayushman Mitra at hospital",
      "Verify identity and generate e-card",
      "Use e-card for cashless treatment at empanelled hospitals",
    ],
    importantInfo:
      "Eligibility is primarily based on the Socio-Economic Caste Census (SECC) 2011. Some states have extended benefits beyond SECC list.",
    matchPercentage: 72,
    state: "All India",
    isCentral: true,
    tags: ["health", "insurance", "hospital", "cashless", "family"],
  },
  {
    id: "nsp-scholarship",
    name: "National Scholarship Portal – OBC Pre-Matric",
    department: "Ministry of Social Justice and Empowerment",
    ministry: "MSJE",
    category: "Education",
    description:
      "Provides pre-matric scholarships to students belonging to Other Backward Classes (OBC) to encourage them to pursue education and reduce dropout rates.",
    benefits: [
      "Day scholars: ₹600–₹700 per month",
      "Hostellers: ₹1,000–₹1,000 per month",
      "Book and stationery allowance",
    ],
    eligibilityCriteria: [
      { label: "Category", value: "OBC student", met: true },
      { label: "Income", value: "Parental income below ₹2.5 lakh per annum", met: true },
      { label: "Class", value: "Class 1 to 10", met: false },
      { label: "Institution", value: "Government or government-aided school", met: true },
    ],
    requiredDocuments: ["Caste Certificate (OBC)", "Income Certificate", "Previous year marksheet", "Bank account"],
    applicationProcess: [
      "Register on scholarships.gov.in (National Scholarship Portal)",
      "Fill application form with required details",
      "Upload supporting documents",
      "Submit before state deadline",
      "Amount transferred directly to bank account",
    ],
    importantInfo:
      "Applications are accepted annually. Deadlines vary by state. Renewal required each academic year.",
    matchPercentage: 59,
    state: "All India",
    isCentral: true,
    tags: ["education", "scholarship", "OBC", "student"],
  },
];

export const mockDocuments: CitizenDocument[] = [
  {
    id: "doc-001",
    name: "Aadhaar Card",
    type: "Identity Proof",
    uploadDate: "2024-11-12",
    status: "Verified",
    fileSize: "842 KB",
    fileType: "PDF",
    extractedFields: [
      { label: "Name", value: "Priya Sharma", confidence: 0.98 },
      { label: "Date of Birth", value: "15/03/1997", confidence: 0.97 },
      { label: "Aadhaar Number", value: "XXXX XXXX 4521", confidence: 0.99 },
      { label: "Address", value: "Pune, Maharashtra - 411001", confidence: 0.94 },
    ],
  },
  {
    id: "doc-002",
    name: "Income Certificate",
    type: "Income Certificate",
    uploadDate: "2024-11-18",
    status: "Verified",
    fileSize: "1.2 MB",
    fileType: "PDF",
    extractedFields: [
      { label: "Name", value: "Priya Sharma", confidence: 0.96 },
      { label: "Annual Income", value: "₹1,85,000", confidence: 0.91 },
      { label: "Issuing Authority", value: "Tehsildar, Pune", confidence: 0.95 },
      { label: "Certificate Number", value: "INC/2024/PNE/8821", confidence: 0.99 },
    ],
  },
  {
    id: "doc-003",
    name: "OBC Caste Certificate",
    type: "Caste Certificate",
    uploadDate: "2024-12-01",
    status: "Needs Review",
    fileSize: "756 KB",
    fileType: "JPG",
    extractedFields: [
      { label: "Name", value: "Priya Sharma", confidence: 0.93 },
      { label: "Category", value: "Other Backward Class (OBC)", confidence: 0.88 },
      { label: "Certificate Date", value: "10/09/2023", confidence: 0.92 },
    ],
  },
  {
    id: "doc-004",
    name: "Graduation Degree",
    type: "Education Certificate",
    uploadDate: "2024-12-05",
    status: "Processing",
    fileSize: "2.1 MB",
    fileType: "PDF",
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-001",
    schemeId: "pm-vishwakarma",
    schemeName: "PM Vishwakarma Yojana",
    department: "Ministry of MSME",
    submittedDate: "2024-12-10",
    lastUpdated: "2025-01-08",
    status: "Under Review",
    referenceNumber: "PMV/2024/MH/192847",
    timeline: [
      { date: "10 Dec 2024", label: "Application Created", description: "Draft application started", done: true },
      { date: "12 Dec 2024", label: "Documents Submitted", description: "All required documents uploaded and verified", done: true },
      { date: "14 Dec 2024", label: "Application Submitted", description: "Application submitted successfully", done: true },
      { date: "08 Jan 2025", label: "Under Review", description: "Application is being reviewed by district authority", done: true, active: true },
      { date: "—", label: "Decision", description: "Pending review completion", done: false },
    ],
    attachedDocuments: ["doc-001", "doc-002"],
    remarks: "Verification of artisan credentials in progress.",
  },
  {
    id: "app-002",
    schemeId: "pmkvy",
    schemeName: "PMKVY 4.0 Skill Training",
    department: "Ministry of Skill Development",
    submittedDate: "2024-11-22",
    lastUpdated: "2024-12-15",
    status: "Approved",
    referenceNumber: "PMKVY/2024/4/MH/77234",
    timeline: [
      { date: "20 Nov 2024", label: "Application Created", description: "Registered on Skill India portal", done: true },
      { date: "22 Nov 2024", label: "Documents Submitted", description: "Aadhaar and bank details verified", done: true },
      { date: "22 Nov 2024", label: "Application Submitted", description: "Course selected and application submitted", done: true },
      { date: "01 Dec 2024", label: "Under Review", description: "Training centre allotment in progress", done: true },
      { date: "15 Dec 2024", label: "Approved", description: "Training batch allotted at Pune centre", done: true },
    ],
    attachedDocuments: ["doc-001"],
  },
  {
    id: "app-003",
    schemeId: "pm-awas-yojana-urban",
    schemeName: "PM Awas Yojana – Urban",
    department: "Ministry of Housing and Urban Affairs",
    lastUpdated: "2025-01-02",
    status: "Draft",
    timeline: [
      { date: "02 Jan 2025", label: "Application Created", description: "Draft started", done: true, active: true },
      { date: "—", label: "Documents Submitted", description: "Pending", done: false },
      { date: "—", label: "Application Submitted", description: "Pending", done: false },
      { date: "—", label: "Under Review", description: "Pending", done: false },
      { date: "—", label: "Decision", description: "Pending", done: false },
    ],
    attachedDocuments: [],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    title: "Application Status Updated",
    message: "Your PM Vishwakarma application (PMV/2024/MH/192847) is now under review by the district authority.",
    category: "Applications",
    isRead: false,
    timestamp: "2025-01-08T10:32:00",
    actionLabel: "View Application",
    actionPath: "/applications/app-001",
  },
  {
    id: "notif-002",
    title: "Document Requires Attention",
    message: "Your OBC Caste Certificate needs re-upload. The image quality is insufficient for verification.",
    category: "Documents",
    isRead: false,
    timestamp: "2025-01-06T14:15:00",
    actionLabel: "Go to Documents",
    actionPath: "/documents",
  },
  {
    id: "notif-003",
    title: "PMKVY Application Approved",
    message: "Your PMKVY 4.0 skill training application has been approved. Training begins 20 January 2025.",
    category: "Applications",
    isRead: true,
    timestamp: "2024-12-15T09:00:00",
    actionLabel: "View Details",
    actionPath: "/applications/app-002",
  },
  {
    id: "notif-004",
    title: "New Scheme Recommendation",
    message: "Based on your profile, you may be eligible for the Ayushman Bharat PM-JAY health scheme.",
    category: "Schemes",
    isRead: true,
    timestamp: "2024-12-10T11:20:00",
    actionLabel: "Check Eligibility",
    actionPath: "/schemes/ayushman-bharat",
  },
  {
    id: "notif-005",
    title: "Profile Completion Reminder",
    message: "Complete your profile to unlock more personalised scheme recommendations.",
    category: "System",
    isRead: true,
    timestamp: "2024-12-08T08:00:00",
    actionLabel: "Complete Profile",
    actionPath: "/profile",
  },
];
